### ISSUE TITLE
Comparison with other SOTA models?

### ISSUE THREAD

**Issue by lucasjinreal** [ekzhang/fastseg#1]
that would be better if there were some comparison with SOTA models such as ENet etc.

**Comment by ekzhang** [comment]
Thanks @jinfagang. I looked at ENet, but the results don't seem as good (after all, it is an older paper). What kind of comparison would be useful for you?

**Comment by lucasjinreal** [comment]
@ekzhang  I didn't catch semantic segmentation field for a long time, may some sota models in 2020?
