### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by rwightman** [ekzhang/fastseg#2]
Cool project, I saw some tweets about it. It's nice to see a working version of MobileNetV3 segmentation and this one looks great.

You leverged the models from https://github.com/rwightman/gen-efficientnet-pytorch and also looks like you adapted my onnx utility scripts. My code is licenesed Apache 2.0 so your obv free to do whatever you will, but attribution is required as per licensing terms. A mention and a link back would be appreciated. Thx

**Comment by ekzhang** [comment]
Thanks @rwightman, your code is really great and made this possible. I do link back to you in the README description (mention `geffnet`), and I'm not duplicating your code here -- it's a pip requirement.

Could you clarify what additional attribution you are looking for?

**Comment by rwightman** [comment]
By link I meant actual link, given that it looks like the onnx scripts that accompanied geffnet were adapted for your use here. I generally try to reference the work I build on top of (or use as a reference) in code docstrings and README and/or license related texts.

**Comment by ekzhang** [comment]
Thanks for clarifying. Actually `onnx_export.py` and `onnx_optimize.py` aren't copied from your code; they are much simpler scripts just based on the PyTorch ONNX documentation. So I'm not sure what I'd write in the docstring, or if it's appropriate. Let me know if you think differently, or just send a PR.

I can definitely add a hyperlink to the README, though! Take a look at c30759e07a52c7370eda11a93396c79f2b141778 and let me know if there's anything else. I'd be very happy to oblige.
