### ISSUE TITLE
EfficientNet Pretrained Weights

### ISSUE THREAD

**Issue by pushkar-khetrapal** [ekzhang/fastseg#4]
Hi, What will be the expected release date of Pretrained Weights of EfficientNet-B0 + LRASPP. Does the accuracy would increased by changing MobileNet v3 with EfficientNet-B0?

**Comment by ekzhang** [comment]
That's a good question. Thanks for looking into `models/efficientnet.py`; that was used in some earlier experiments. Unfortunately I'm not currently planning to release the EfficientNet-B0 pretrained weights, due to how similar the model is to MobileNetV3-Large-100. I do not believe the accuracy improved significantly.

**Comment by pushkar-khetrapal** [comment]
Okay, Thanks @ekzhang for clearing the doubt. I'm trying to add two other heads for bounding boxes and classes upon your code. So, I thought the efficientNet-B0 would work fine than MobileNetV3 because the number of weights increase gradually. Can you guide me which backbone would preferable for classes + bounding boxes + semantic heads at good FPS?

**Comment by ekzhang** [comment]
Sounds like you might be looking for [Panoptic Segmentation](https://arxiv.org/abs/1801.00868). Maybe start from looking at architectures like [EfficientPS](http://panoptic.cs.uni-freiburg.de/)?

**Comment by pushkar-khetrapal** [comment]
Yes, kind of Panoptic Segmentation but without Instance Mask. The EfficientPS code isn't publicly available right now. And the architecture is too big of Panoptic Segmentation, I can't get good FPS. So, I'm trying to build on smaller backbone.

**Comment by ekzhang** [comment]
Got it, thanks for clarifying. Feel free to use this repository as a starting point to base your code on (you might find `lraspp.py` useful). EfficientNet sounds like a reasonable backbone choice; I just don't have the compute capabilities at the moment to release pretrained weights for it, so you would need to train those yourself.

**Comment by pushkar-khetrapal** [comment]
Okay, I'll look into `lraspp.py`. Thanks alot for your suggestions. And also thanks for sharing this repository, really saved many days of mine.
