### ISSUE TITLE
Training on Mapillary

### ISSUE THREAD

**Issue by amil-rp-work** [ekzhang/fastseg#5]
Hey @ekzhang 
I have got access to the Mapillary dataset, however, I wanted to know how will I get about training a model on it?

**Comment by ekzhang** [comment]
Hi @amil-rp-work, I haven't used the Mapillary vistas dataset, but I don't believe it is very different. Have you tried the training scripts here? https://github.com/NVIDIA/semantic-segmentation

**Comment by amil-rp-work** [comment]
Thanks for the reference, will try it and re-open if something is a miss 👍
